apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../bases
resources:
  - application.yaml
  - console-link.yaml
patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
  - path: patch-role-binding.yaml
    target:
      kind: RoleBinding