- op: replace
  path: /metadata/name
  value: quarkus-app
- op: add
  path: /spec/destination/namespace
  value: quarkus
- op: add
  path: /spec/source
  value:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.tls.enabled
          value: "true"
        - name: image.name
          value: quay.io/ablock/gitops-helm-quarkus
    chart: quarkus
    repoURL: https://redhat-developer.github.io/redhat-helm-charts
    targetRevision: 0.0.3


